/**
 * @license
 * Copyright 2020 Carles Ferrando Garcia (ferrando_cariga@gva.es)
 * SPDX-License-Identifier: BSD-3-Clause
 */

var MSG = {
    title: "BDuino",
    appName: "BlocklyDuino",
    blocks: "Bloques",
    prog: "Programa",
    catLogic: "Lógica",
    catLoops: "Bucles",
    catMath: "Matemáticas",
    catText: "Texto",
    catLists: "Listas",
    catColour: "Color",
    catVariables: "Variables",
    catFunctions: "Funciones",
    listVariable: "lista",
    textVariable: "texto",
    screenshot: "Descarga una captura de pantalla",
    xmlError: "No se puede descargar vuestro fichero guardado. Quizás se ha creado con un versión diferente de BlocklyDuino?",
    badXml: "Error de análisis XML:\n%1\n\nSelecciona 'De acuerdo' para abandonar los cambios o 'Cancela' para continuar editando el fichero.",
    languageSpan: "escoge idioma",
    interfaceColorSpan: "tema de interfaz",
    codeEditorColorSpan: "tema del editor de código",
    themeSpan: "escoge tema",
    renderSpan: "escoge renderizador",
    fullScreenButton_span: "pantalla completa",
    undoButton_span: "Deshaz",
    redoButton_span: "Rehaz",
    boardButtonSpan: "listar placas",
    verifyButton_span: "Verifica código",
    serialButtonSpan: "listar puerto COM",
    uploadButton_span: "Carga",
    serialConnectButton_span: "Monitor serie",
    saveCodeButton_span: "Exporta código Arduino",
    newButton_span: "Proyecto nuevo",
    save_span: "¿Guardar nombre del fichero?",
    saveXMLButton_span: "Guarda fichero BlocklyDuino",
    loadXMLfakeButton_span: "Carga fichero BlocklyDuino",
    loadXML_span: "¿Reemplazar bloques existentes?\n'Cancelar' los fusionará.",
    loadXML_error_span: "Error al analizar XML:\n",
    resetButton_span: "Restablece BlocklyDuino",
    resetQuestion_span: "Restablecer BlocklyDuino y",
    helpButton_span: "ayuda",
    helpModalSpan_title: "Ayuda - Acerca de",
    helpModalSpan_text:
        '<table>' +
        '<tbody>' +
        '<tr>' +
        '<td style="width: 142px;"><img src="./blocklyduino/media/logo_only.png" alt="" width="129" height="144" /></td>' +
        '<td>' +
        '<p style="text-align: left;"><strong>BlocklyDuino</strong></p>' +
        '<p style="text-align: left;">BlocklyDuino es un <strong>programa web de edición y programación visual por bloques para placas <a href="https://www.arduino.cc/">Arduino</a></strong>. Está basado en <a href="https://developers.google.com/blockly/">Blockly</a>, el editor gráfico de programación en línea, y en el trabajo realizado en <a href="https://github.com/A-S-T-U-C-E/STudio4Education">STudio4Education</a>, un proyecto similar para placas <a href="https://www.st.com/">STmicroelectronics</a>.</p>' +
        '<p style="text-align: left;">BlocklyDuino proporciona un entorno de programación por bloques y su traducción a código C de \'Arduino\'.</p>' +
        '</td>' +
        '</tr>' +
        '</tbody>' +
        '</table>' +
        '<p style="text-align: left;">Accesibilidad: <a href="https://github.com/BlocklyDuino/BlocklyDuino-v2#accessibility">documentación en línea</a>.</p>' +
        '<p style="text-align: left;">Documentación oficial: <a href="https://developers.google.com/blockly/guides/configure/web/keyboard-nav" rel="nofollow">Blockly developers</a>.</p>' +
        '<p style="text-align: left;">Wiki: <a href="http://www.libreduc.cc/wiki">en LibrEduc</a>.</p>' +
        '<p style="text-align: left;">¿Un bug? Publícalo aquí: <a href="https://github.com/BlocklyDuino/BlocklyDuino-v2/issues">en Github</a>.</p>' +
        '<p style="text-align: center;">v0.8.0 - licencia GNU GPL versión 3 - Sébastien CANET',
    //menu tools
    toolsButton_span: "herramientas",
    wiringButton_span: "cableado",
    factoryButton_span: "fábrica de bloques",
    htmlButton_span: "fábrica HTML",
    colorConversionButton_span: "codificación de colores",
    dataConversionButton_span: "codificación de datos",
    //menu IoT
    iotConnectButton_span: "servidores",
    launchWebServer_span: "servidor local",
    papyrusConnect_span: "Conectar con Papyrus",
    registerToOrchestrator_span: "Conectar con Arrowhead",
    blynkConnect_span: "Conectar con Blynk",
    //ace editor
    editorReadOnlyToggle_span: "editor de código editable o de solo lectura",
    copyCodeButton_span: "Copia código a portapapeles",
    //lateral panel
    accessibilitySpan: "habilita modo accesibilidad",
    defaultCursorSpan: "Cursor por defecto",
    basicCursorSpan: "Cursor básico",
    lineCursorSpan: "Cursor línea",
    keyMappingSpan: "abre asignaciones de teclado",
    themeClassicSpan: "Clásico",
    themeModernSpan: "Moderno",
    themeDeuteranopiaSpan: "Deuteranopia/Protanopia",
    themeTritanopiaSpan: "Tritanopia",
    themeZelosSpan: "Zelos",
    themeHighContrastSpan: "Alto contraste",
    themeDarkSpan: "Oscuro",
    themeBwSpan: "Negro & Blanco",
    compilationInProgress: "Placa",
    keyMappingModalSpan: "Establece asignaciones de teclado",
    detailedCompilation_span: "Compilación detallada con mensajes",
    CLI_title_span: "gestión del compilador",
    installBoard_title_span: "instalar placa en CLI",
    searchlLib_title_span: "buscar una biblioteca",
    installLib_title_span: "instalar biblioteca en CLI",
    actionName0: "previo",
    actionName1: "siguiente",
    actionName2: "entra al bloque",
    actionName3: "sal del bloque",
    actionName4: "insertar",
    actionName5: "marca",
    actionName6: "desconectar",
    actionName7: "Caja de herramientas",
    actionName8: "salir",
    actionName9: "mueve el cursor del espacio de trabajo arriba",
    actionName10: "mueve el cursor del espacio de trabajo abajo",
    actionName11: "mueve el cursor del espacio de trabajo a la izquierda",
    actionName12: "mueve el cursor del espacio de trabajo a la derecha",
    actionName13: "conmuta la navegación por teclado",
    setup_sideButton_span: "configuración",
    config_UI_title_span: "interfaz",
    displaySpan: "elección de visualización",
    displayChoiceButtons: "solo botones",
    displayChoiceBandT: "botones + texto",
    displayChoiceText: "solo texto",
    fontSpan: "elección de fuente",
    fontSizeSpan: "renderización",
    optionFontSizeBlocks: "Tamaño de fuente de bloques",
    optionFontSizePage: "Tamaño de fuente de página",
    optionFontSpacingPage: "Espaciado de fuente de página",
    //CLI_functions.js
    CLI_githubLinkButton_span: "documentación",
    coreUpdateButton_msg: "Se está actualizando...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    cleanCLIcacheButton_msg: "Se está limpiando...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    cleanCLIcacheButton_error_msg: "Error al suprimir la carpeta .\\tmp",
    cleanCLIcacheButton_success_msg: "¡Limpiado!",
    listBoardsButton_msg: "Se está buscando la placa...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    installBoardsButton_msg: "Se está instalando el soporte de la placa, espera...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    searchlLibButton_msg: "Se está buscando la biblioteca...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    installLibButton_msg: "Se está instalando la biblioteca...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    coreUpdateButton_span: "actualizar núcleo y bibliotecas",
    cleanCLIcacheButton_span: "limpiar caché",
    listBoardsButton_span: "detección y listado de placas",
    installBoardsInput_span: "nombre de la placa a instalar",
    installBoardsButton_span: "instalar este tipo de placa",
    searchlLibInput_span: "nombre de la biblioteca a buscar",
    searchlLibButton_span: "buscar esta biblioteca",
    installLibInput_span: "nombre de la biblioteca a instalar",
    installLibButton_span: "instalar esta biblioteca",
    //categories panel
    categories_title_span: "elección de categorías",
    //arrowhead panel
    iot_title_span: "control IoT",
    //modals
    boardListModalHeader_span: "Lista de placas",
    boardListModalButton_span: "Detalles",
    boardModal_connect: "Conector",
    boardModal_voltage: "Voltaje de funcionamiento",
    boardModal_voltage_normal: "Voltaje de funcionamiento (recomendado)",
    boardModal_voltage_maxi: "Voltaje de funcionamiento (límites)",
    boardModal_cpu: "Microcontrolador µC",
    boardModal_speed: "Velocidad del reloj",
    boardModal_inout: "Número de E/S lógicas",
    boardModal_in_analog: "Número de E/S analógicas",
    boardModal_out_analog: "Número de salidas PWM",
    boardModal_i_max_out: "Corriente máx. por pin (5V)",
    boardModal_i_max3: "Corriente máx. de salida en pin 3.3V",
    boardModal_i_max_5: "Corriente máx. de salida en pin 5V",
    boardModal_flash: "Memoria Flash",
    boardModal_sram: "Memoria SRAM",
    boardModal_eeprom: "EEPROM",
    portListModalHeader_span: "Lista de puertos COMM",
    //IDE_functions.js
    IDE_connect: 'Conectar al puerto ',
    IDE_select_port: '¡Selecciona un puerto!',
    IDE_select_board: '¡Selecciona una placa!',
    IDE_verif_progress: '\nVerificación: en progreso...\n<i class="fa fa-spinner fa-pulse fa-1_5x fa-fw"></i>',
    IDE_verif_ok: '\nVerificación: OK',
    IDE_upload1: 'Placa ',
    IDE_upload2: ' en puerto ',
    IDE_upload3: '\nCarga: en progreso...\n<i class="fa fa-spinner fa-pulse fa-1_5x fa-fw"></i>',
    IDE_upload_ok: '\nCarga: OK',
    serial_btn_start: "<span class='fa fa-play'></span> Iniciar",
    serial_info_stop: 'detenido<br>',
    serial_btn_stop: "<span class='fa fa-pause'></span> Detener",
    serial_info_start: 'comunicación iniciada<br>',
    serial_CSV: 'Exportar datos a CSV',
    inputTextSerial: 'Texto',
    btn_serialSend_span: 'Enviar',
    btn_serialConnect_span: 'Iniciar',
    btn_serialPeekClear_span: 'Limpiar',
    btn_serialPeekCSV_span: 'Exportar',
    btn_serialChart_span: 'Gráfica',
    btn_serialChartPause_span: 'Iniciar'
};
