name=ESP32Synth
version=2.3.5
author=Danilo Gabriel
maintainer=Danilo Gabriel
sentence=Sintetizador Polifonico Profissional de 80 canais para ESP32.
paragraph=Suporta I2S, DAC interno e PDM. Inclui Tracker engine e WaveTable synthesis.
category=Signal Input/Output
url=https://github.com/danilogcrf2-oss/ESP32Synth
architectures=esp32,esp32s3
includes=ESP32Synth.h

